---
name: KeepExp
version: 0.0.2+dev
main: NhanAZ\KeepExp\Main
api: 5.0.0
src-namespace-prefix: NhanAZ\KeepExp
website: https://github.com/NhanAZ
author: NhanAZ
description: Prevents players from losing experience on death
...
